ROADEF pbs tuning

diff --git a/tuning_setups/tuning_EVRP_EA/target-evaluator b/tuning_setups/tuning_EVRP_EA/target-evaluator
--- a/tuning_setups/tuning_EVRP_EA/target-evaluator
+++ b/tuning_setups/tuning_EVRP_EA/target-evaluator
@@ -62,7 +62,7 @@ COST=$(tail -n 1 ${STDOUT} 2> /dev/null | grep -e '^[[:space:]]*[+-]\?[0-9]' | c
 
 if ! [[ $COST =~ ^[0-9]+$ ]]
 then
-    echo instance $CONFIG_FILE failed for some reason >& 2
+#    echo instance $CONFIG_FILE failed for some reason >& 2
     echo 1000000000
 else
     rm -f "${STDOUT}" "${STDERR}"  "${CONFIG_FILE}"
